site_name: Siddhi-IO-HTTP
extra_css:
- stylesheets/extra.css
extra_javascript:
- javascripts/extra.js
site_favicon: images/favicon.ico
extra:
  logo: images/siddhi-logo-w.svg
  palette:
    primary: teal
    accent: teal
google_analytics:
- UA-103065-28
- auto
pages:
- Welcome to WSO2 Siddhi IO HTTP: index.md
- API Docs:
  - 1.0.30: api/1.0.30.md
  - 1.0.29: api/1.0.29.md
  - 1.0.28: api/1.0.28.md
  - 1.0.27: api/1.0.27.md
  - 1.0.26: api/1.0.26.md
  - 1.0.25: api/1.0.25.md
  - 1.0.24: api/1.0.24.md
  - 1.0.22: api/1.0.22.md
  - 1.0.21: api/1.0.21.md
  - 1.0.20: api/1.0.20.md
  - 1.0.19: api/1.0.19.md
  - 1.0.18: api/1.0.18.md
  - 1.0.17: api/1.0.17.md
  - 1.0.16: api/1.0.16.md
  - 1.0.15: api/1.0.15.md
  - 1.0.14: api/1.0.14.md
  - 1.0.13: api/1.0.13.md
  - 1.0.12: api/1.0.12.md
  - 1.0.11: api/1.0.11.md
  - 1.0.10: api/1.0.10.md
  - 1.0.4: api/1.0.4.md
  - latest: api/latest.md
- License: license.md
theme: material
